# Generated by Django 5.2.4 on 2026-01-12 00:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(help_text='Client-generated unique identifier stored in sessionStorage', max_length=255, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the session ended', null=True)),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Number of pages viewed in this session')),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total session duration in seconds')),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=50)),
                ('is_bounce', models.BooleanField(default=False, help_text='True if user left after viewing only one page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Session Metrics',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('page_load', 'Page load'), ('share', 'Share')], max_length=50)),
                ('page_url', models.URLField(help_text="Full URL of the page where the activity occurred (e.g., 'https://techhive.com/articles/intro-to-react')", max_length=500)),
                ('referrer', models.URLField(blank=True, help_text="Source URL that led to this page (e.g., 'https://google.com/search', 'https://twitter.com/post/123', 'https://techhive.com/home')", max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of activity in seconds')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data (job_id, article_id, etc.)')),
                ('load_time_ms', models.PositiveIntegerField(blank=True, help_text='Page load time in milliseconds (measured on frontend)', null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='analytics.sessionmetrics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['session_id'], name='analytics_s_session_6c9864_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['user', 'start_time'], name='analytics_s_user_id_721c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['is_bounce'], name='analytics_s_is_boun_6665e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id'], name='analytics_u_session_0e759b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='analytics_u_timesta_2b8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id', 'timestamp'], name='analytics_u_session_f19d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['device_type', 'timestamp'], name='analytics_u_device__8f8fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_u_event_t_12ec8a_idx'),
        ),
    ]
