# Generated by Django 5.2.4 on 2026-01-01 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0028_liveblockswebhookevent_articleworkflowhistory'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(help_text='Date for this metrics snapshot. Each date can only have one metrics record to prevent duplicate daily aggregations.', unique=True)),
                ('registered_users_count', models.PositiveIntegerField(default=0)),
                ('visitors_count', models.PositiveIntegerField(default=0, help_text='Anonymous visitors count')),
                ('total_active_users', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Percentage of single-page sessions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in minutes')),
                ('mobile_count', models.PositiveIntegerField(default=0)),
                ('tablet_count', models.PositiveIntegerField(default=0)),
                ('desktop_count', models.PositiveIntegerField(default=0)),
                ('avg_load_speed', models.FloatField(default=0.0, help_text='Average page load speed in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_24cb73_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(help_text='Client-generated unique identifier stored in sessionStorage', max_length=255, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the session ended', null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total session duration in seconds')),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=50)),
                ('is_bounce', models.BooleanField(default=False, help_text='True if user left after viewing only one page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('job', 'Job'), ('event', 'Event')], max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('object_id', models.CharField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, help_text="Source URL that led to this page (e.g., 'https://google.com/search', 'https://twitter.com/post/123', 'https://techhive.com/home')", max_length=500, null=True)),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time spent viewing content')),
                ('content_type_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_views', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to='analytics.sessionmetrics')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('scroll', 'Scroll'), ('click', 'Click'), ('share', 'Share'), ('reaction', 'Reaction'), ('comment', 'Comment'), ('save', 'Save'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=50)),
                ('page_url', models.URLField(max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of activity in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data (scroll_depth, article_id, etc.)')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='analytics.sessionmetrics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_read_time', models.FloatField(default=0.0, help_text='Average read time in minutes')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage of users who completed reading', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Calculated as (total_engagements / views) * 100')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='content.article')),
            ],
            options={
                'verbose_name_plural': 'Article Analytics',
                'ordering': ['-total_views'],
                'indexes': [models.Index(fields=['article'], name='analytics_a_article_071959_idx'), models.Index(fields=['total_views'], name='analytics_a_total_v_cce495_idx'), models.Index(fields=['last_updated'], name='analytics_a_last_up_5aa065_idx'), models.Index(fields=['engagement_rate'], name='analytics_a_engagem_b8850b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['session_id'], name='analytics_s_session_6c9864_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['user', 'start_time'], name='analytics_s_user_id_721c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['is_bounce'], name='analytics_s_is_boun_6665e4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['content_type', 'content_id', 'timestamp'], name='analytics_c_content_d9ca92_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_c_user_id_f212bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['device_type', 'timestamp'], name='analytics_c_device__2f37c6_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['session_id'], name='analytics_c_session_48b23d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['referrer'], name='analytics_c_referre_480295_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id'], name='analytics_u_session_0e759b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='analytics_u_timesta_2b8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id', 'timestamp'], name='analytics_u_session_f19d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['device_type', 'timestamp'], name='analytics_u_device__8f8fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_u_event_t_12ec8a_idx'),
        ),
    ]
