# Generated by Django 5.2.4 on 2026-01-01 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmetrics',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages viewed in this session'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
