# Generated by Django 5.2.4 on 2026-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_sessionmetrics_page_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmetrics',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Session Metrics'},
        ),
        migrations.AlterField(
            model_name='articleanalytics',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Number of distinct users who viewed this article (counted once per user, regardless of multiple visits)'),
        ),
        migrations.AlterField(
            model_name='contentview',
            name='content_id',
            field=models.CharField(help_text='UUID of the content being tracked (e.g., Article, Job, or Event ID)'),
        ),
    ]
