# Generated by Django 5.2.4 on 2026-01-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_sessionmetrics_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleanalytics',
            name='article',
        ),
        migrations.RemoveField(
            model_name='contentview',
            name='content_type_model',
        ),
        migrations.RemoveField(
            model_name='contentview',
            name='session',
        ),
        migrations.RemoveField(
            model_name='contentview',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyMetrics',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='load_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Page load time in milliseconds (measured on frontend)', null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('page_load', 'Page load'), ('click', 'Click'), ('share', 'Share')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional event-specific data (job_id, article_id, etc.)'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='referrer',
            field=models.URLField(blank=True, help_text="Source URL that led to this page (e.g., 'https://google.com/search', 'https://twitter.com/post/123', 'https://techhive.com/home')", max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleAnalytics',
        ),
        migrations.DeleteModel(
            name='ContentView',
        ),
    ]
