# Generated by Django 5.2.4 on 2026-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_articleanalytics_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('page_load', 'Page load'), ('share', 'Share')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='page_url',
            field=models.URLField(help_text="Full URL of the page where the activity occurred (e.g., 'https://techhive.com/articles/intro-to-react')", max_length=500),
        ),
    ]
