# Generated by Django 5.2.4 on 2025-08-03 21:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_options_event_category_job_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='title', editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='name', editable=False, populate_from='name'),
        ),
    ]
