# Generated by Django 5.2.4 on 2025-08-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
