# Generated by Django 5.2.4 on 2025-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_article_published_at_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.tag'),
        ),
    ]
