# Generated by Django 5.2.4 on 2025-08-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_article', 'Can publish article'), ('can_archive_article', 'Can archive article'), ('can_request_revisions', 'Can request revisions'), ('can_submit_for_review', 'Can submit for review')]},
        ),
    ]
