# Generated by Django 5.2.4 on 2025-08-21 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_article_options_alter_article_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_for_review', 'Submitted for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('review_completed', 'Review Completed'), ('ready_for_publishing', 'Ready for Publishing'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='savedarticle',
            unique_together={('article', 'user')},
        ),
    ]
