# Generated by Django 5.2.4 on 2025-08-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='content_tag_name_52ccf1_idx'),
        ),
    ]
