# Generated by Django 5.2.4 on 2025-10-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_job_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-created_at']},
        ),
    ]
