# Generated by Django 5.2.4 on 2025-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_event_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
