# Generated by Django 5.2.4 on 2025-10-14 15:00

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_resource_is_featured_tool_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[apps.common.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/', validators=[apps.common.validators.validate_file_size]),
        ),
    ]
