# Generated by Django 5.2.4 on 2025-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
