# Generated by Django 5.2.4 on 2025-10-27 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_article_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='replying_to',
            field=models.ForeignKey(blank=True, help_text='The user being replied to (for mentions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent'], name='content_com_article_9f68c9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'active'], name='content_com_article_6037bc_idx'),
        ),
    ]
