# Generated by Django 5.2.4 on 2025-10-27 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_comment_options_comment_replying_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reply_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='content_com_article_9f68c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='content_com_article_6037bc_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='commentthread',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='content.article'),
        ),
        migrations.AddField(
            model_name='commentthread',
            name='root_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread_root', to='content.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.commentthread'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', '-created_at'], name='content_com_thread__b37f60_idx'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['article', 'is_active'], name='content_com_article_18af33_idx'),
        ),
    ]
