# Generated by Django 5.2.4 on 2025-11-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_rename_active_comment_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replying_to',
        ),
    ]
