# Generated by Django 5.2.4 on 2025-12-26 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_article_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='content_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time content was synced from Liveblocks', null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When review was completed (approved/rejected/changes requested)', null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text="Private notes for reviewer's reference only", null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When reviewer started the review', null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='content_art_assigne_6c86b5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['assigned_editor', 'status'], name='content_art_assigne_8d1bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='content_art_status_fc7162_idx'),
        ),
        migrations.AddIndex(
            model_name='articlereview',
            index=models.Index(fields=['article', 'status'], name='content_art_article_9b250d_idx'),
        ),
        migrations.AddIndex(
            model_name='articlereview',
            index=models.Index(fields=['reviewed_by', 'status', 'is_active'], name='content_art_reviewe_35140e_idx'),
        ),
    ]
