# Generated by Django 5.2.4 on 2025-12-26 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_article_options_article_assigned_editor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveblocksWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(help_text='Type of webhook event (storageUpdated, notificationEvent, etc.)', max_length=50)),
                ('room_id', models.CharField(help_text='Liveblocks room ID (e.g., article-123)', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether the event was successfully processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_id', '-created_at'], name='content_liv_room_id_585dea_idx'), models.Index(fields=['processed', '-created_at'], name='content_liv_process_d19f20_idx'), models.Index(fields=['event_type', '-created_at'], name='content_liv_event_t_07c4db_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleWorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted_for_review', 'Submitted for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('ready_for_publishing', 'Ready for Publishing'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted_for_review', 'Submitted for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('ready_for_publishing', 'Ready for Publishing'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the status change', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='content.article')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Article Workflow Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['article', '-changed_at'], name='content_art_article_8b890c_idx')],
            },
        ),
    ]
