# Generated by Django 5.2.4 on 2026-01-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_liveblockswebhookevent_articleworkflowhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='created_at',
        ),
    ]
