# Generated by Django 5.2.4 on 2026-01-06 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_articlereview_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articlereview',
            name='content_art_reviewe_35140e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='articlereview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='articlereview',
            index=models.Index(fields=['reviewed_by', 'status'], name='content_art_reviewe_b8443c_idx'),
        ),
        migrations.RemoveField(
            model_name='articlereview',
            name='is_active',
        ),
    ]
