# Generated by Django 5.2.4 on 2026-01-10 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_remove_articlereview_content_art_reviewe_35140e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
