# Generated by Django 5.2.4 on 2026-01-12 21:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_articlereview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='def', editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='def', editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='def', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='def', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
