# Generated by Django 5.2.4 on 2026-01-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_event_is_active_event_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_active',
        ),
    ]
