# Generated by Django 5.2.4 on 2026-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_remove_event_is_active_remove_job_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Google Developer Groups', max_length=250),
            preserve_default=False,
        ),
    ]
