# Generated by Django 5.2.4 on 2026-01-16 00:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='agenda',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Event Agenda'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Job Requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Job Responsibilities'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Resource Body'),
        ),
    ]
