# Generated by Django 5.2.4 on 2025-11-19 12:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text="Plan name (e.g., 'Premium Monthly')", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Plan description for display')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Naira (e.g., 5000.00)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('features', models.TextField()),
                ('paystack_plan_code', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='TRIALING', help_text='Current subscription status', max_length=20)),
                ('paystack_subscription_code', models.CharField(help_text='Subscription code from Paystack (e.g., SUB_abc123xyz)', max_length=50, unique=True)),
                ('paystack_customer_code', models.CharField(help_text='Customer code from Paystack (e.g., CUS_abc123xyz)', max_length=50)),
                ('paystack_authorization_code', models.CharField(help_text='Authorization code for charging card (e.g., AUTH_abc123xyz)', max_length=50)),
                ('card_last4', models.CharField(blank=True, help_text="Last 4 digits of card (e.g., '1234')", max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, help_text="Card type (e.g., 'visa', 'mastercard')", max_length=20, null=True)),
                ('card_bank', models.CharField(blank=True, help_text="Issuing bank (e.g., 'Access Bank')", max_length=50, null=True)),
                ('start_date', models.DateTimeField(help_text='When subscription started')),
                ('trial_start', models.DateTimeField(blank=True, help_text='When trial period started', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='When trial period ends', null=True)),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period')),
                ('next_billing_date', models.DateTimeField(blank=True, help_text='When next charge will happen', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When user clicked cancel', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When subscription actually expires', null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Should subscription auto-renew?')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancel when current period ends (deferred cancellation)')),
                ('payment_failed_at', models.DateTimeField(blank=True, help_text='When payment first failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of automatic retry attempts made')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='When last retry attempt was made', null=True)),
                ('cancel_reason', models.TextField(blank=True, help_text='Why user cancelled (optional feedback)', null=True)),
                ('user', models.OneToOneField(help_text='User who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='The premium plan user is subscribed to', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(help_text="Event type (e.g., 'subscription.create')", max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload from Paystack')),
                ('signature', models.CharField(help_text='Paystack signature for verification', max_length=255)),
                ('processed', models.BooleanField(default=False, help_text='Has this webhook been processed?')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When webhook was processed', null=True)),
                ('error', models.TextField(blank=True, help_text='Any errors during processing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When webhook was received')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='subscriptio_event_t_6bec6a_idx'), models.Index(fields=['processed'], name='subscriptio_process_35a1bd_idx'), models.Index(fields=['-created_at'], name='subscriptio_created_f02480_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(help_text='Our internal reference (e.g., TXN_abc123xyz)', max_length=100, unique=True)),
                ('paystack_reference', models.CharField(help_text="Paystack's transaction reference", max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='NGN', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20)),
                ('transaction_type', models.CharField(choices=[('SUBSCRIPTION', 'New Subscription'), ('RENEWAL', 'Monthly Renewal'), ('RETRY', 'Automatic Retry'), ('MANUAL_RETRY', 'Manual Retry'), ('REACTIVATION', 'Reactivation')], help_text='What triggered this transaction', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, help_text='When transaction was initiated')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was successful', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When payment failed', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Why payment failed (from Paystack)', null=True)),
                ('is_retry', models.BooleanField(default=False, help_text='Is this a retry attempt?')),
                ('retry_number', models.IntegerField(blank=True, help_text='Which retry attempt (1, 2, 3)', null=True)),
                ('paystack_response', models.JSONField(blank=True, help_text='Full response from Paystack API', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['reference'], name='subscriptio_referen_6fed03_idx'), models.Index(fields=['paystack_reference'], name='subscriptio_paystac_187232_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['paystack_subscription_code'], name='subscriptio_paystac_1890a1_idx'),
        ),
    ]
