# Generated by Django 5.2.4 on 2025-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymenttransaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='signature',
            field=models.CharField(blank=True, help_text='Paystack signature for verification', max_length=255, null=True),
        ),
    ]
