# Generated by Django 5.2.4 on 2025-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_webhooklog_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='payload',
            field=models.JSONField(blank=True, help_text='Full webhook payload from Paystack', null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='signature',
            field=models.CharField(default='dggg', help_text='Paystack signature for verification', max_length=255),
            preserve_default=False,
        ),
    ]
