# Generated by Django 5.2.4 on 2025-11-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_webhooklog_payload_alter_webhooklog_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paystack_email_token',
            field=models.CharField(blank=True, help_text='Token for managing subscription on Paystack (e.g., d7gofp6yppn3qz7)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reference',
            field=models.CharField(default='abc', help_text='Custom reference', max_length=20),
            preserve_default=False,
        ),
    ]
