# Generated by Django 5.2.4 on 2025-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_paymenttransaction_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of current billing period', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of current billing period', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, help_text='Authorization code for charging card (e.g., AUTH_abc123xyz)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, help_text='Customer code from Paystack (e.g., CUS_abc123xyz)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, help_text='Subscription code from Paystack (e.g., SUB_abc123xyz)', max_length=50, null=True),
        ),
    ]
