# Generated by Django 5.2.4 on 2025-12-12 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_paymenttransaction_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='subscriptio_paystac_187232_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='paystack_reference',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(help_text='Subscription refrence', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'New Subscription'), ('RENEWAL', 'Monthly Renewal')], help_text='What triggered this transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reference',
            field=models.CharField(help_text='Custom reference', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='TRIALING', help_text='Current subscription status', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
    ]
