# Generated by Django 5.2.4 on 2025-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_remove_paymenttransaction_subscriptio_paystac_187232_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default=None, help_text='Current subscription status', max_length=20, null=True),
        ),
    ]
