# Generated by Django 5.2.4 on 2025-12-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency code', max_length=3),
        ),
    ]
