# Generated by Django 5.2.4 on 2025-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_remove_user_created_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('reviewer', 'Reviewer'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
