# Generated by Django 5.2.4 on 2025-08-05 20:35

import apps.accounts.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, null=True, populate_from=apps.accounts.models.slugify_two_fields),
            preserve_default=False,
        ),
    ]
