# Generated by Django 5.2.4 on 2025-08-05 20:35

from django.db import migrations
import uuid

def gen_username(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for row in User.objects.all():
        row.username = uuid.uuid4()
        row.save(update_fields=["username"])
        
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        migrations.RunPython(gen_username, reverse_code=migrations.RunPython.noop),
    ]
