# Generated by Django 5.2.4 on 2025-08-05 20:35

from django.db import migrations
import apps.accounts.models
import autoslug.fields

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250805_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=apps.accounts.models.slugify_two_fields, unique=True),
            preserve_default=False,
        ),
    ]
