# Generated by Django 5.2.4 on 2025-11-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_be_mentioned',
            field=models.BooleanField(default=True),
        ),
    ]
