# Generated by Django 5.2.4 on 2025-11-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_can_be_mentioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_be_mentioned',
        ),
        migrations.AddField(
            model_name='user',
            name='mentions_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
