# Generated by Django 5.2.4 on 2025-11-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_can_be_mentioned_user_mentions_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
