# Generated by Django 5.2.4 on 2025-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#4ECDC4', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
    ]
