# Generated by Django 5.2.4 on 2026-01-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_cursor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#BB8FCE', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
    ]
