# Generated by Django 5.2.4 on 2026-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_cursor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#52B788', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
    ]
