# Generated by Django 5.2.4 on 2026-01-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_cursor_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted_at',
            new_name='suspended_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Admin suspension flag. When True, account is suspended by staff for policy violations. Takes priority over user_active. User cannot self-reactivate. Check this AFTER email verification but BEFORE user_active. If True, show suspension reason and support contact.'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#45B7D1', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Django's authentication gate. Keep True to allow custom account status checks in views. If False, Django blocks authentication before our custom logic runs, preventing granular error messages. We manage account access through is_email_verified, user_active, and is_suspended instead."),
        ),
    ]
