# Generated by Django 5.2.4 on 2026-01-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_deleted_at_user_suspended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#4ECDC4', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
    ]
