# Generated by Django 5.2.4 on 2026-01-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_cursor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cursor_color',
            field=models.CharField(default='#45B7D1', help_text='Hex color for Liveblocks cursor and mentions', max_length=7),
        ),
    ]
