# Generated by Django 5.2.4 on 2025-11-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
