# Generated by Django 5.2.4 on 2025-07-29 17:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_about_contact_rename_created_newsletter_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('body', models.TextField()),
                ('fb', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()])),
                ('ln', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()])),
                ('x', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()])),
                ('ig', models.CharField(max_length=250, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
