# Generated by Django 5.2.4 on 2025-07-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_sitedetail_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
