# Generated by Django 5.2.4 on 2026-01-15 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribe_token',
            field=models.CharField(default='token', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
