#!/bin/bash

# Start Celery worker
celery -A clothing_store worker --loglevel=info --pool=solo &

# Start Celery Beat (scheduler)
celery -A clothing_store beat --loglevel=info &

# Keep the script running
wait